- name: scope
  become: True
  tags:
    - reverse_proxy
  block:
    - name: install nginx
      ansible.builtin.package:
        name:
          - nginx
          - nginx-mod-stream
        state: present

    - name: nginx config for reverse proxy
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
        owner: root
        group: root
      notify: restart nginx

    - name: permit traffic in default zone for servives http and https
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
      notify: restart firewalld

    - name: ensure service is enabled started
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started
      register: reverse_proxy__nginx_service_state
