services:
  nextcloud:
    image: nextcloud@sha256:e80b83febbc5aba4c04d201b0d1ada744d1119d510248954f8d4105891cf5ddd # 31.0.6-fpm-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=/var/run/postgresql
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - PGSSLCERT=/tmp/postgresql.crt
      - REDIS_HOST=/var/run/redis/redis.sock
      - REDIS_HOST_PORT=0
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - ONLYOFFICE_SERVER=${ONLYOFFICE_FQDN}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_FQDN}
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_USER}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - ONLYOFFICE_JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=1024M
      - TRUSTED_PROXIES=${INTERNAL_REVERSE_PROXY_IP}
      - OVERWRITECLIURL=https://${NEXTCLOUD_FQDN}
      - OVERWRITEPROTOCOL=https
    user: "82:1000"
    extra_hosts:
      - "${NEXTCLOUD_FQDN}:${NEXTCLOUD_IP}"
      - "${ONLYOFFICE_FQDN}:${ONLYOFFICE_IP}"
    read_only: false
    volumes:
      - nextcloud:/var/www/html:rw
      - nextcloud_data:/var/www/data:rw
      - nextcloud_socket:/var/run/php:rw
      - db_socket:/var/run/postgresql:rw
      - redis_socket:/var/run/redis:rw
      - ./nextcloud/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:rw
      - ./nextcloud/nextcloud-config.sh:/docker-entrypoint-hooks.d/before-starting/nextcloud-config.sh:ro
      - ./nextcloud/nextcloud-apps.sh:/docker-entrypoint-hooks.d/before-starting/nextcloud-apps.sh:ro
      - ./nextcloud/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./nextcloud/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    networks:
      - external-net    # nextcloud needs internet access
    depends_on:
      - db
      - nextcloud-redis
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  # This is a root container!
  # Probably we do not need all those env vars...
  nextcloud-cron:
    image: nextcloud@sha256:e80b83febbc5aba4c04d201b0d1ada744d1119d510248954f8d4105891cf5ddd # 31.0.6-fpm-alpine
    restart: unless-stopped
    entrypoint: /cron.sh
    user: "0:1000"
    depends_on:
      - nextcloud
    environment:
      - POSTGRES_HOST=/var/run/postgresql
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${NEXTCLOUD_DB_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - PGSSLCERT=/tmp/postgresql.crt
      - REDIS_HOST=/var/run/redis/redis.sock
      - REDIS_HOST_PORT=0
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_FQDN}
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_USER}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - OVERWRITECLIURL=https://${NEXTCLOUD_FQDN}
      - OVERWRITEPROTOCOL=https
    extra_hosts:
      - "${NEXTCLOUD_FQDN}:${NEXTCLOUD_IP}"
      - "${ONLYOFFICE_FQDN}:${ONLYOFFICE_IP}"
    read_only: true
    volumes:
      - nextcloud:/var/www/html:rw
      - nextcloud_data:/var/www/data:rw
      - db_socket:/var/run/postgresql:rw
      - redis_socket:/var/run/redis:rw
      - ./nextcloud/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:ro
      - ./nextcloud/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./nextcloud/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    networks:
      - external-net    # nextcloud needs internet access
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  onlyoffice:
    image: onlyoffice/documentserver-ee@sha256:f6219abc67561a57d5ad3307a6aa816b291280fad40a43475f0335329dbdaa75 # 9.0.0.168
    restart: unless-stopped
    # Custom entrypoint: write license first, then start the document server
    entrypoint: ["/bin/sh", "-c", "/write-license.sh && /app/ds/run-document-server.sh"]
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=${ONLYOFFICE_DB_USER}
      - DB_PWD=${ONLYOFFICE_DB_PASSWORD}
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - SSL_CERTIFICATE_PATH=/var/www/onlyoffice/Data/certs/live/${ONLYOFFICE_FQDN}/fullchain.pem
      - SSL_KEY_PATH=/var/www/onlyoffice/Data/certs/live/${ONLYOFFICE_FQDN}/privkey.pem
      - PGSSLCERT=/tmp/postgresql.crt
      - ONLYOFFICE_LICENSE
    user: "0:1000"
    depends_on:
      - db
    networks:
      - onlyoffice-db-net
      - external-net
    extra_hosts:
      - "${NEXTCLOUD_FQDN}:${NEXTCLOUD_IP}"
      - "${ONLYOFFICE_FQDN}:${ONLYOFFICE_IP}"
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data:rw
      - onlyoffice_logs:/var/log/onlyoffice:rw
      - onlyoffice_lib:/var/lib/onlyoffice:rw
      - onlyoffice_certs_archive:/var/www/onlyoffice/Data/certs/archive/${ONLYOFFICE_FQDN}:ro
      - onlyoffice_certs_live:/var/www/onlyoffice/Data/certs/live/${ONLYOFFICE_FQDN}:ro
      - ./onlyoffice/write-license.sh:/write-license.sh:ro
    ports:
      - "8443:443"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
      - CAP_KILL
      - CAP_SETGID
      - CAP_SETUID
      - CAP_SYS_PTRACE

  db:
    image: postgres@sha256:ef2235fd13b6cb29728a98ee17862ff5c9b7d20515a9b34804da4a45062695f6 # 16-alpine
    # Setting suggestions by https://pgtune.leopard.in.ua with this input:
    # DB Version: 16
    # OS Type: linux
    # DB Type: web
    # Total Memory (RAM): 4 GB
    # CPUs num: 4
    # Connections num: 30
    # Data Storage: san
    command: >
      postgres
        -c listen_addresses='0.0.0.0'
        -c logging_collector=off
        -c log_destination='stderr'
        -c log_min_duration_statement=200
        -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d '
        -c max_connections='30'
        -c shared_buffers='1GB'
        -c effective_cache_size='3GB'
        -c maintenance_work_mem='256MB'
        -c checkpoint_completion_target='0.9'
        -c wal_buffers='16MB'
        -c default_statistics_target='100'
        -c random_page_cost='1.1'
        -c effective_io_concurrency='300'
        -c work_mem='30840kB'
        -c huge_pages='off'
        -c min_wal_size='1GB'
        -c max_wal_size='4GB'
        -c max_worker_processes='4'
        -c max_parallel_workers_per_gather='2'
        -c max_parallel_workers='4'
        -c max_parallel_maintenance_workers='2'
    restart: unless-stopped
    user: "70:1000"
    depends_on:
      - init
    environment:
      - NEXTCLOUD_DB=nextcloud
      - ONLYOFFICE_DB=onlyoffice
      - POSTGRES_PASSWORD
      - NEXTCLOUD_DB_USER
      - NEXTCLOUD_DB_PASSWORD
      - ONLYOFFICE_DB_USER
      - ONLYOFFICE_DB_PASSWORD
    read_only: true
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - db_run:/var/run/postgresql:rw
      - db_socket:/var/run/postgresql:rw
      - ./postgresql/create-pg_hba_conf.sh:/docker-entrypoint-initdb.d/create-pg_hba_conf.sh:ro
      - ./postgresql/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh:ro
    networks:
      - onlyoffice-db-net
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run

  nextcloud-redis:
    image: redis@sha256:48501c5ad00d5563bc30c075c7bcef41d7d98de3e9a1e6c752068c66f0a8463b # 8.0.2-alpine
    restart: unless-stopped
    # Setting socket permissions to 777 is a workaround to nextcloud can access it.
    # As the redis user and the nextcloud user share the same group (1000), it should
    # be sufficient to set the permissions to 770. But for some unknown reason this
    # does not work. So 777 is a workaround.
    command: >
      redis-server
        --unixsocket /var/run/redis/redis.sock
        --unixsocketperm 777
        --port 0
        --requirepass "$REDIS_HOST_PASSWORD"
    user: "999:1000"
    depends_on:
      - init
    environment:
      - REDIS_HOST_PASSWORD
    volumes:
      - redis_socket:/var/run/redis:rw
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /data:uid=999,gid=1000,mode=770

  nginx-proxy:
    image: nginxinc/nginx-unprivileged@sha256:8265b1df5a89cc1a0a067e472bf47aca7cee52f0561c98a0dff91312dcdd8adb # 1.25.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    read_only: true
    volumes:
      - nextcloud_socket:/var/run/php:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nextcloud_certs_archive:/etc/nginx/certs/archive/${NEXTCLOUD_FQDN}:ro
      - nextcloud_certs_live:/etc/nginx/certs/live/${NEXTCLOUD_FQDN}:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
      - ./nginx/99_nextcloud_fpm_status_credentials.sh:/docker-entrypoint.d/99_nextcloud_fpm_status_credentials.sh:ro
    environment:
      - NEXTCLOUD_FPM_STATUS_CREDENTIALS
    depends_on:
      - certbot
    networks:
      - external-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: "101:1000"  # nginx user in Alpine image
    tmpfs:
      - /var/cache/nginx:uid=101,gid=1000,mode=700
      - /tmp
      - /run:uid=101,gid=1000,mode=700

  init:
    image: alpine@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715 # 3.20.6
    command: >
      sh -c " \
        chown -R 101:1000 /etc/letsencrypt /var/log/letsencrypt /var/lib/letsencrypt &&
        chown -R 70:1000 /var/run/postgresql && chmod -R g+w /var/run/postgresql && \
        chown -R 999:1000 /var/run/redis && chmod -R g+w /var/run/redis && \
        chown -R 82:1000 /var/run/php && chmod -R g+w /var/run/php \
      "
    volumes:
      - nextcloud_certs_archive:/etc/letsencrypt/archive/${NEXTCLOUD_FQDN}:rw
      - nextcloud_certs_live:/etc/letsencrypt/live/${NEXTCLOUD_FQDN}:rw
      - onlyoffice_certs_archive:/etc/letsencrypt/archive/${ONLYOFFICE_FQDN}:rw
      - onlyoffice_certs_live:/etc/letsencrypt/live/${ONLYOFFICE_FQDN}:rw
      - certbot_config:/etc/letsencrypt:rw
      - certbot_logs:/var/log/letsencrypt:rw
      - certbot_work:/var/lib/letsencrypt:rw
      - nextcloud_socket:/var/run/php:rw
      - db_socket:/var/run/postgresql:rw
      - redis_socket:/var/run/redis:rw
    restart: "no"

  certbot:
    image: certbot/dns-cloudflare@sha256:bf87c2e3588f08c7fd520cc2fd155a954850c68d92105d693b26cd12dc3fca28 # v4.1.1
    restart: unless-stopped
    user: "101:1000"  # Ein normaler User ohne Rootrechte
    depends_on:
      - init
    read_only: true
    volumes:
      - nextcloud_certs_archive:/etc/letsencrypt/archive/${NEXTCLOUD_FQDN}:rw
      - nextcloud_certs_live:/etc/letsencrypt/live/${NEXTCLOUD_FQDN}:rw
      - onlyoffice_certs_archive:/etc/letsencrypt/archive/${ONLYOFFICE_FQDN}:rw
      - onlyoffice_certs_live:/etc/letsencrypt/live/${ONLYOFFICE_FQDN}:rw
      - ./certbot/run-certbot.sh:/run-certbot.sh:ro
      - certbot_config:/etc/letsencrypt:rw
      - certbot_logs:/var/log/letsencrypt:rw
      - certbot_work:/var/lib/letsencrypt:rw
    entrypoint: /run-certbot.sh
    environment:
      - NEXTCLOUD_FQDN
      - ONLYOFFICE_FQDN
      - CERTBOT_EMAIL
      - CLOUDFLARE_API_TOKEN
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp

volumes:
  nextcloud:
  nextcloud_data:
  nextcloud_certs_archive:
  nextcloud_certs_live:
  nextcloud_socket:
  onlyoffice_data:
  onlyoffice_logs:
  onlyoffice_lib:
  onlyoffice_certs_archive:
  onlyoffice_certs_live:
  db_data:
  db_run:
  db_socket:
  nginx_html:
  certbot_config:
  certbot_logs:
  certbot_work:
  redis_socket:

networks:
  onlyoffice-db-net:
    internal: true
    ipam:
      config:
        - subnet: ${ONLYOFFICE_DB_SUBNET}
  external-net:
    internal: false
