services:
  nextcloud:
    image: nextcloud:28.0.2-fpm-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - PGSSLCERT=/tmp/postgresql.crt
      - REDIS_HOST=nextcloud-redis
      - SMTP_HOST=www623.your-server.de
      - SMTP_PORT=587
      - SMTP_SECURE=starttls
      - SMTP_AUTHTYPE=LOGIN
      - MAIL_FROM_ADDRESS=nextcloud
      - MAIL_DOMAIN=fairagro.net
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.fairagro.net
      # these variables are set via secrets:
      # (TODO:we could alternatively rely on docker secrets, but it's unclear if this
      # is also supported by the postgres database container/
      # refer to: https://docs.docker.com/compose/how-tos/use-secrets/,
      # We would need to define all variables ending in _FILE instead)
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - SMTP_NAME
      - SMTP_PASSWORD
      - REDIS_HOST_PASSWORD
    user: "82:1000"
    read_only: false
    volumes:
      - nextcloud_data:/var/www/html:rw
      - redis-session_ini:/usr/local/etc/php/conf.d/redis-session.ini:rw
      - ./nextcloud/nextcloud-config.sh:/docker-entrypoint-hooks.d/before-starting/nextcloud-config.sh:ro
      - ./nextcloud/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - "9000"  # FPM
      - "9001"  # FPM status
    networks:
      - nextcloud-db-net
      - nextcloud-redis-net
      - nextcloud-nginx-net
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  # This is a root container!
  # Probably we do not need all those env vars...
  nextcloud-cron:
    image: nextcloud:28.0.2-fpm-alpine
    restart: unless-stopped
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - PGSSLCERT=/tmp/postgresql.crt
      - REDIS_HOST=nextcloud-redis
      - SMTP_HOST=www623.your-server.de
      - SMTP_PORT=587
      - SMTP_SECURE=starttls
      - SMTP_AUTHTYPE=LOGIN
      - MAIL_FROM_ADDRESS=nextcloud
      - MAIL_DOMAIN=fairagro.net
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.fairagro.net
      # these variables are set via secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - SMTP_NAME
      - SMTP_PASSWORD
      - REDIS_HOST_PASSWORD
    read_only: true
    volumes:
      - nextcloud_data:/var/www/html:rw
      - redis-session_ini:/usr/local/etc/php/conf.d/redis-session.ini:ro
      - ./nextcloud/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - nextcloud-db-net
      - nextcloud-redis-net
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true

  nextcloud-db:
    image: postgres:15
    # Setting suggestions by https://pgtune.leopard.in.ua with this input:
    # DB Version: 15
    # OS Type: linux
    # DB Type: web
    # Total Memory (RAM): 4 GB
    # CPUs num: 4
    # Connections num: 30
    # Data Storage: san
    command: >
      postgres
        -c listen_addresses='nextcloud-db'
        -c log_min_duration_statement='200'
        -c max_connections='30'
        -c shared_buffers='1GB'
        -c effective_cache_size='3GB'
        -c maintenance_work_mem='256MB'
        -c checkpoint_completion_target='0.9'
        -c wal_buffers='16MB'
        -c default_statistics_target='100'
        -c random_page_cost='1.1'
        -c effective_io_concurrency='300'
        -c work_mem='30840kB'
        -c huge_pages='off'
        -c min_wal_size='1GB'
        -c max_wal_size='4GB'
        -c max_worker_processes='4'
        -c max_parallel_workers_per_gather='2'
        -c max_parallel_workers='4'
        -c max_parallel_maintenance_workers='2'
    restart: always
    environment:
      - POSTGRES_DB=nextcloud
      # folgende variablen werden via secret gesetzt:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    read_only: true
    volumes:
      - nextcloud_db_data:/var/lib/postgresql/data:rw
    networks:
      - nextcloud-db-net
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /run

  nextcloud-redis:
    image: redis:alpine
    restart: always
    command: >
      redis-server
      --bind nextcloud-redis
      --requirepass "$REDIS_HOST_PASSWORD"
    environment:
      # folgende variablen werden via secret gesetzt:
      - REDIS_HOST_PASSWORD
    networks:
      - nextcloud-redis-net
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /data

  nginx-proxy:
    image: nginxinc/nginx-unprivileged:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    read_only: true
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud_data:/var/www/html:ro
      - ./nginx/99_nextcloud_fpm_status_credentials.sh:/docker-entrypoint.d/99_nextcloud_fpm_status_credentials.sh:ro
    environment:
      - NEXTCLOUD_FPM_STATUS_CREDENTIALS
    depends_on:
      - certbot
    networks:
      - nextcloud-nginx-net
      - external-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: "101:1000"  # nginx user in Alpine image
    tmpfs:
      - /var/cache/nginx:uid=101,gid=1000,mode=700
      - /tmp
      - /run:uid=101,gid=1000,mode=700

  certbot_init:
    image: alpine
    command: sh -c "chown -R 101:1000 /etc/letsencrypt /var/log/letsencrypt /var/lib/letsencrypt"
    volumes:
      - nginx_certs:/etc/letsencrypt:rw
      - certbot_logs:/var/log/letsencrypt:rw
      - certbot_work:/var/lib/letsencrypt:rw
    restart: "no"

  certbot:
    image: certbot/dns-cloudflare
    restart: "no"
    user: "101:1000"  # Ein normaler User ohne Rootrechte
    depends_on:
      - certbot_init
    read_only: true
    volumes:
      - nginx_certs:/etc/letsencrypt:rw
      - ./certbot/run-certbot.sh:/run-certbot.sh:ro
      - certbot_logs:/var/log/letsencrypt:rw
      - certbot_work:/var/lib/letsencrypt:rw
    entrypoint: /run-certbot.sh
    environment:
      - CERTBOT_DOMAINS=nextcloud.fairagro.net
      # folgende variablen werden via secret gesetzt:
      - CERTBOT_EMAIL
      - CLOUDFLARE_API_TOKEN
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
      
  certbot-renew:
    image: certbot/dns-cloudflare
    restart: unless-stopped
    user: "101:1000"
    depends_on:
      - certbot
    read_only: true
    volumes:
      - nginx_certs:/etc/letsencrypt:rw
      - ./certbot/certbot-renew.sh:/certbot-renew.sh:ro
      - certbot_logs:/var/log/letsencrypt:rw
      - certbot_work:/var/lib/letsencrypt:rw
    entrypoint: /certbot-renew.sh
    environment:
      # folgende variablen werden via secret gesetzt:
      - CLOUDFLARE_API_TOKEN
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp

volumes:
  nextcloud_data:
  nextcloud_db_data:
  redis-session_ini:
  nginx_certs:
  nginx_html:
  certbot_logs:
  certbot_work:

networks:
  nextcloud-db-net:
    internal: true
  nextcloud-redis-net:
    internal: true
  nextcloud-nginx-net:
    internal: true
  external-net:
    internal: false
