- name: restart fail2ban
  become: True
  tags:
    - fail2ban
  # only restart if not just started
  when: not ((fail2ban__service_state is defined) and (fail2ban__service_state.changed))
  ansible.builtin.service:
    name: fail2ban
    state: restarted
